[manifest]
version = "1.0.0"
dump_lua = true
priority = 3

[[patches]]
[patches.pattern]
target = 'functions/misc_functions.lua'
pattern = "jokers = {tally = 0, of = 0},"
position = 'before'
match_indent = true
payload = '''
techniques = {tally = 0, of = 0},
managers = {tally = 0, of = 0},
'''

[[patches]]
[patches.pattern]
target = 'functions/misc_functions.lua'
pattern = "if v.set and ((v.set == 'Joker') or v.consumeable or (v.set == 'Edition') or (v.set == 'Voucher') or (v.set == 'Back') or (v.set == 'Booster')) then"
position = 'at'
match_indent = true
overwrite = true
payload = '''
local sp = v.special or (v.config and type(v.config.extra) == 'table' and v.config.extra.special)
if v.set and (
    (v.set == 'Joker' and v.ptype and v.mod and v.mod.id == 'Pokerleven') or
    v.consumeable or
    (sp and (sp == "Technique" or sp == "Manager" or sp == "Spirit")) or
    (v.set == 'Edition') or
    (v.set == 'Voucher') or
    (v.set == 'Back') or
    (v.set == 'Booster')
) then'''

[[patches]]
[patches.pattern]
target = 'functions/misc_functions.lua'
pattern = "if v.set and v.set == 'Joker' then"
position = 'at'
overwrite = true
match_indent = true
payload = '''
local sp = v.special or v.special_type or (v.config and type(v.config.extra) == 'table' and v.config.extra.special)
if sp == "Technique" then
    G.DISCOVER_TALLIES.techniques.of = G.DISCOVER_TALLIES.techniques.of+1
    if v.discovered then G.DISCOVER_TALLIES.techniques.tally = G.DISCOVER_TALLIES.techniques.tally+1 end
elseif sp == "Manager" then
    G.DISCOVER_TALLIES.managers.of = G.DISCOVER_TALLIES.managers.of+1
    if v.discovered then G.DISCOVER_TALLIES.managers.tally = G.DISCOVER_TALLIES.managers.tally+1 end
elseif v.set and v.set == 'Joker' and sp == nil and v.ptype and v.mod and v.mod.id == 'Pokerleven' then
'''

[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = "local alert_joker, alert_voucher, alert_tarot, alert_planet, alert_spectral, alert_blind, alert_edition, alert_tag, alert_seal, alert_booster = false,false,false,false,false,false,false,false,false,false"
position = 'at'
overwrite = true
match_indent = true
payload = '''
local alert_manager, alert_technique, alert_joker, alert_voucher, alert_tarot, alert_planet, alert_spectral, alert_blind, alert_edition, alert_tag, alert_seal, alert_booster = false,false,false,false,false,false,false,false,false,false,false,false
'''

[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = "if v.set == 'Joker' then alert_joker = true end"
position = 'at'
match_indent = true
payload = '''
local sp = v.special or (v.config and type(v.config.extra) == 'table' and v.config.extra.special)
if v.set == 'Joker' and not sp and v.mod and v.mod.id == 'Pokerleven' then alert_joker = true end
if v.set == 'Joker' and sp and sp == "Technique" then alert_technique = true end
if v.set == 'Joker' and sp and sp == "Manager" then alert_manager = true end
'''

[[patches]]
[patches.pattern]
target = 'functions/misc_functions.lua'
pattern = "if v.set == 'Joker' and not v.no_collection and not v.omit then"
position = 'at'
match_indent = true
payload = '''
if v.set == 'Joker' and not v.no_collection and not v.omit and v.mod and v.mod.id == 'Pokerleven' then
'''

[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = "{id = 'your_collection_boosters', alert_uibox_name = 'your_collection_boosters_alert'},"
position = 'after'
match_indent = true
payload = '''
{id = 'your_collection_techniques', alert_uibox_name = 'your_collection_techniques_alert'},
{id = 'your_collection_managers', alert_uibox_name = 'your_collection_managers_alert'},
'''

[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = "G.ARGS.set_alerts_alertables[11].should_alert = alert_booster"
position = 'after'
match_indent = true
payload = '''
G.ARGS.set_alerts_alertables[12].should_alert = alert_technique
G.ARGS.set_alerts_alertables[13].should_alert = alert_manager
'''
